### ISSUE TITLE
Cannot change volume when app is on

### ISSUE THREAD

**Issue by AskoldMakaruk** [x13a/Volta#2]
My phone is ![Screenshot_2022-02-05-13-37-43-96_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://user-images.githubusercontent.com/18248541/152640497-cc06fa4c-bf2d-43ea-9ce5-735b93622ba9.jpg)

I turned app on and it prevents me from changing my volume with buttons when screen is on.

**Comment by x13a** [comment]
You have to write steps to reproduce this. Is music playing? Is flashlight checked? What version do you use? And much more..

**Comment by x13a** [comment]
Closing on inactivity
