### ISSUE TITLE
Accessibility service is unavailable

### ISSUE THREAD

**Issue by MintyRoma** [x13a/Volta#3]
🐞From time to time daemon dies with message "Accessibility service is unavailable". Restarting Volta in Accessibility Settings fix this, but it has a small chance that volume buttons will misclick or make double click. 

📱Technical info
Phone: Realme 7 Pro
Android: 11
Launcher: RealmeUI 2.0
Volta: 1.0.3

**Comment by x13a** [comment]
I suppose that it is not a daemon dies, but the daemon was killed. It was a
murder.

Before I uploaded Volta to Play Store every day Google's finsky process
related to Play Protect killed the app. Now it is working as expected. BTW
I installed the version from Play Store. About misclick, could you clarify
what do you mean?

**Comment by MintyRoma** [comment]
When you press volume up without holding button phone turns up volume more than 1 volume point (same with volume down). Sometimes 2 points, sometimes 5..

**Comment by x13a** [comment]
For this I have no idea what can go wrong. Anyway I uploaded a new version
recently.

First of all, if you have Google services, install the app from Play Store.
We have to find who is a murderer.

After that check for service unavailable on daily basis. In my situation
finsky killed it every day.

If this won't help, then logs will tell us more.

**Comment by MintyRoma** [comment]
Unfortunately uploading to Google Play not fixed kills. Application still dies after ~1 day. But as I can see misclicks were fixed.![Screenshot_2022-02-16-10-50-17-14_f29364753e6e414c78d8d38d8a6ce63c.jpg](https://user-images.githubusercontent.com/47593328/154219961-f7fcea52-e6cf-4fe4-b6ae-bbf9b275d02f.jpg)

**Comment by x13a** [comment]
And you excluded Volta from all battery optimizations?

**Comment by MintyRoma** [comment]
Yes. But still dies

**Comment by x13a** [comment]
Than logs. Cannot say if this will help us, but we can try to find a murderer. Please install: [LogcatReader](https://github.com/darshanparajuli/LogcatReader). You have to grant `READ_LOGS` permission via `adb`. The app will show you what to do. Then you can filter logs by the package name `me.lucky.volta`.

If you do not know what to look up, you can save them to file, upload to Google Drive (or any other) and send a message with the link to `44uaanjm0@relay.firefox.com`. I will look them, maybe will find something helpful.

**Comment by x13a** [comment]
Closing on inactivity
