### ISSUE TITLE
Feature to pause music playback

### ISSUE THREAD

**Issue by AnonymousSeal** [x13a/Volta#4]
First things first, I really like your app :)

I think, it would be super useful to be able to stop and start playback via the volume buttons, too. Maybe by clicking volume up and down at the same time...

**Comment by x13a** [comment]
I will think of it. Thx)

**Comment by x13a** [comment]
> clicking volume up and down at the same time

Is too hard for many people, plus depending of your device model it can be hard to do with the hand you want. More over some times it is used for accessibility as I remember. Than we returned to double up/down.

**Comment by AnonymousSeal** [comment]
Hmm... Maybe you could make the three gestures remapable. I actually never really need the previous option. Main features I need are start/stop, next and the flashlight. I'm sure this is different for different people and customizable settings are probably the best.
I could make this into a saperate issue if you want to.

**Comment by x13a** [comment]
There is no problems with splitting track on next / previous options. But
for customization it is better to look at Key Mapper.

**Comment by AnonymousSeal** [comment]
Thanks, cool recommendation. I am using Keymapper now and since the latest Volta update, I can also use the flashlight feature, since I can disable the playback gestures. I couldn't replicate the 'dont listen to double clicks, when media is playing' logic in keymapper so I'm pretty happy that I can also use your project.
