### ISSUE TITLE
Feature: Bluetooth volume buttons

### ISSUE THREAD

**Issue by georgettica** [x13a/Volta#7]
The app is great if I use the phone for volume up/down..
But I want to use it from my Bluetooth headset 

Let me know how I can help to make it happen

**Comment by x13a** [comment]
Hard to say if I can do smth about it. 
I have a bluetooth speaker and will try experiment with it.

**Comment by georgettica** [comment]
More than I can ask for.
Thanks!

**Comment by georgettica** [comment]
If this is the case we can only hope that the accessibility service will expose the volume buttons of the Bluetooth.

I am fine with closing this for now and hoping this feature will be implemented on the newer versions
